//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphBuilder
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraphEdge
    {
        public int EdgeID { get; set; }
        public int BaseNodeID { get; set; }
        public int AddressNodeID { get; set; }
        public int GraphID { get; set; }
        public int Weight { get; set; }
    
        public virtual GraphNode GraphNode { get; set; }
        public virtual GraphNode GraphNode1 { get; set; }
        public virtual GraphStructure GraphStructure { get; set; }
    }
}
