//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphBuilder
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraphNode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GraphNode()
        {
            this.GraphEdge = new HashSet<GraphEdge>();
            this.GraphEdge1 = new HashSet<GraphEdge>();
        }
    
        public int NodeID { get; set; }
        public double PosX { get; set; }
        public double PosY { get; set; }
        public int GraphID { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GraphEdge> GraphEdge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GraphEdge> GraphEdge1 { get; set; }
        public virtual GraphStructure GraphStructure { get; set; }
    }
}
