//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphBuilder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkedNodeList
    {
        public int ID { get; set; }
        public Nullable<int> NodeID { get; set; }
        public Nullable<bool> Marked { get; set; }
        public Nullable<int> DistFromStart { get; set; }
        public Nullable<int> PrevNode { get; set; }
    }
}
